name: Testing schedule

on:
  schedule:
   - cron: 1 * * * *

jobs:
   print-output:
      runs-on: ubuntu-latest
      steps:
      - name: printing the schedule
        run: echo "Printing the schedule..."

