name: Testing schedule

on: push

jobs:
   print-output:
      runs-on: ubuntu-latest
      steps:
      - name: printing the schedule
        run: echo "Printing the schedule... ${{ github.event.schedule }}"

