name: Testing schedule

on:
  schedule:
   - cron: "*/5 * * * *"

jobs:
   print-output:
      runs-on: ubuntu-latest
      steps:
      - name: printing the schedule
        run: echo "Printing the schedule... ${{ github.event.schedule }}"

